### ISSUE TITLE
Couldn't connect to socket (Libre Office)

### ISSUE THREAD

**Issue by chickencoder** [crossroadchurch/malachi#3]
Error on Ubuntu 17.10

Traceback (most recent call last):
  File "malachi_server.py", line 583, in <module>
    m = MalachiServer()
  File "malachi_server.py", line 24, in __init__
    self.ph = PresentationHandler()
  File "/home/jesse/projects/malachi/PresentationHandler.py", line 23, in __init__
    context = resolver.resolve("uno:socket,host=localhost,port=2002;urp;StarOffice.ComponentContext")
PresentationHandler.NoConnectException: Connector : couldn't connect to socket (Success)

Assuming this is because I need to install Libre office etc.

**Comment by nikukatansa** [comment]
Yeah, you'll need LibreOffice installed and then run soffice --accept="socket,host=localhost,port=2002;urp" --quickstart in a separate terminal before starting malachi_server.py.  Check out https://github.com/crossroadchurch/malachi/wiki/System-requirements-and-dependencies for other Python dependencies
